"""
Report Generator & Quality Control Engine.
Generates structured Markdown, HTML, and JSON reports.
Enforces Section 38 Quality Control gates before report finalization.
"""

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from app.core.enums import FindingStatus
from app.core.redactor import SecurityRedactor
from app.database.models import Finding


@dataclass
class QualityControlResult:
    """Result of report readiness audit."""
    is_ready: bool
    failures: List[str]
    checks_passed: int
    total_checks: int


class ReportQualityControl:
    """Validates finding suitability before report generation."""

    @classmethod
    def audit(cls, finding: Finding) -> QualityControlResult:
        failures = []

        if not finding.affected_asset:
            failures.append("Target asset is undefined.")

        if finding.status == FindingStatus.FALSE_POSITIVE:
            failures.append("Finding is marked as FALSE_POSITIVE.")

        if not finding.evidence_items or len(finding.evidence_items) == 0:
            failures.append("No primary evidence attached to finding.")

        if not finding.business_impact and not finding.technical_impact:
            failures.append("No technical or business impact documented.")

        if not finding.remediation:
            failures.append("Remediation advice is missing.")

        if not finding.human_reviewed and finding.status == FindingStatus.REPORTED:
            failures.append("Human review has not occurred.")

        total_checks = 6
        passed = total_checks - len(failures)
        return QualityControlResult(
            is_ready=len(failures) == 0,
            failures=failures,
            checks_passed=passed,
            total_checks=total_checks,
        )


class ReportGenerator:
    """Generates Markdown, HTML, and JSON security reports."""

    @classmethod
    def generate_markdown(cls, finding: Finding, program_name: str) -> str:
        """Produce standardized Markdown bug bounty report."""
        evidence_str = "\n".join([f"- Evidence ID: `{ev.id}` ({ev.evidence_type})" for ev in finding.evidence_items]) or "None recorded"

        md = f"""# Vulnerability Report: {finding.title}

## Program
- **Program**: {program_name}
- **Affected Asset**: `{finding.affected_asset}`
- **Endpoint**: `{finding.endpoint or 'N/A'}`

## Classification
- **Severity**: {finding.severity.value}
- **Confidence**: {finding.confidence.value}
- **OWASP Category**: {finding.owasp_category.value if finding.owasp_category else 'N/A'}
- **CWE**: {finding.cwe_id or 'N/A'}
- **Lifecycle Status**: {finding.status.value}

---

## Executive Summary
{finding.description}

## Business & Technical Impact
- **Business Impact**: {finding.business_impact or 'N/A'}
- **Technical Impact**: {finding.technical_impact or 'N/A'}

## Evidence & Verification
{evidence_str}

## Remediation & Defensive Recommendations
{finding.remediation or 'Implement strict boundary controls, parameter validation, and rate limiting.'}

---
*Report generated by BugBounty-AI platform with automated evidence validation.*
"""
        return SecurityRedactor.redact_text(md)

    @classmethod
    def export_report(cls, finding: Finding, program_name: str, output_path: str, format: str = "md") -> str:
        """Export report to filesystem."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        if format.lower() == "json":
            data = {
                "id": finding.id,
                "title": finding.title,
                "program": program_name,
                "asset": finding.affected_asset,
                "endpoint": finding.endpoint,
                "severity": finding.severity.value,
                "status": finding.status.value,
                "owasp": finding.owasp_category.value if finding.owasp_category else None,
                "cwe": finding.cwe_id,
                "description": finding.description,
                "impact": finding.technical_impact,
                "remediation": finding.remediation,
            }
            content = json.dumps(SecurityRedactor.redact_dict(data), indent=2)
        else:
            content = cls.generate_markdown(finding, program_name)

        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

        return str(path)
